image: Visual Studio 2017

version: 1.9.{build}.0
# Major_Version_Number.Minor_Version_Number.Build_Number.Revision_Number

branches:
    only:
        - master

environment:
    COMPILER: msvc
    VSVER: 14.1

    matrix:
        - QT: C:\Qt\5.11.2\msvc2017_64
          PLATFORM: amd64
        - QT: C:\Qt\5.11.2\winrt_x64_msvc2017
          PLATFORM: x86
init:
    - ps: |
        $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
        $packageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Revision
        $env:build_number = $version.Build
        $env:rolisteam_version = $packageVersion

# scripts that run after cloning repository
install:
    - set PATH=%QT%\bin\;C:\Qt\Tools\QtCreator\bin\;C:\Qt\QtIFW3.0.1\bin\;%PATH%

# scripts that run before build
before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # After calling vcvarsall.bat, %PLATFORM% will be X64 or x86
    - qmake --version
    - mkdir build
    - cd build
    - qmake -r -spec win32-msvc CONFIG+=x86_64 CONFIG-=debug CONFIG+=release ../rolisteam.pro
    #- if "%PLATFORM%" EQU "x86" (qmake -r -spec win32-msvc CONFIG+=Win32 CONFIG-=debug CONFIG+=release ../rolisteam.pro)

# custom build scripts
build_script:
    - nmake

# scripts that run after build
after_build:
    - mkdir distrib\rolisteam
    - windeployqt.exe --dir .\distrib\rolisteam %APPVEYOR_BUILD_FOLDER%\build\client\rolisteam.exe
    - copy "%APPVEYOR_BUILD_FOLDER%\build\client\rolisteam.exe" "distrib\rolisteam\rolisteam.exe"
    - copy "%APPVEYOR_BUILD_FOLDER%\README.md" "distrib\rolisteam\README.md"
    - copy "%APPVEYOR_BUILD_FOLDER%\LICENSE" "distrib\rolisteam\LICENSE.txt"
    - echo %flameshot_version% > "distrib\rolisteam\version.txt"
    - echo Build:%build_number% >> "distrib\rolisteam\version.txt"
    - echo %APPVEYOR_REPO_COMMIT% >> "distrib\rolisteam\version.txt"
    - copy "distrib\flameshot\rolisteam.exe" "distrib\rolisteam_win_%PLATFORM%.exe"
    - copy "%APPVEYOR_BUILD_FOLDER%\build\translations\Internationalization_*.qm" "distrib\rolisteam\translations"
    # Delete translations\qt_*.qm
    - del /F /Q "distrib\rolisteam\translations\qt_*.qm"
    # Copy OpenSSL DLLs
    - cd distrib
    - 7z a rolisteam_%rolisteam_version%_win_%PLATFORM%.zip rolisteam
    - appveyor-retry curl --upload-file ./rolisteam_%rolisteam_version%_win_%PLATFORM%.zip https://transfer.sh/rolisteam_%rolisteam_version%_win_%PLATFORM%.zip


# artifacts:
#     - path: build\distrib\flameshot_win_%PLATFORM%_portable_%flameshot_version%.zip
#       name: portable
#     - path: build\distrib\flameshot_win_%PLATFORM%.exe
#       name: exe_only

